site_name: Taller de Godot
docs_dir: 'sources'
site_dir: 'docs'


nav:
  - "1. Introducció": '1.intro.md'
  - "2. Personatge": '2.personatge.md'
  - "3. Enemics": '3.enemics.md'
  - "4. Mans a l'obra": '4.todo.md'
  

theme:
  name: 'material'
  custom_dir: 'overrides'
  logo: 'img/logo.svg'
  favicon: 'img/logo.svg'
  features:
    - content.code.copy # Per copiar codi

#extra_css:
#  - https://joamuran.net/curs24_25/css/material-just.css

plugins:
  - search
  - glightbox   # Per vore les imatges en gran quan fas clic en elles.
  - macros      # Per suporatar macros i afegir el nav a la pàgina principal
  #- exclude-unused-files:
  #    file_types_to_check: ["png", "jpg", "jpeg", "gif"]
  #    enabled: true

markdown_extensions:
  - attr_list           # Permet incorporar atributs a les imatges { width=100px }
  - md_in_html # Junt a attr_list per afegir peus a les imatges
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - toc:
      baselevel: 2
      toc_depth: 3
      title: Continguts
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
